[build]
  command = "next build"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "pk_21403368a51635b2d116007194fcfa6b5c287ad6f1362"